# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [2]:
# Write your answer here

import numpy as np

# 1-D array of zeros with 10 elements
zeros = np.zeros(10)

# 1-D array of vowels
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# 2-D array of ones with 2 rows and 5 columns (dtype=int)
ones = np.ones((2, 5), dtype=int)

# 2-D array using nested lists
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

# 2-D array using arange with start=4, step=4, dtype=float
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# Output to check the arrays
print("zeros:\n", zeros)
print("\nvowels:\n", vowels)
print("\nones:\n", ones)
print("\nmyarray1:\n", myarray1)
print("\nmyarray2:\n", myarray2)



zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

vowels:
 ['a' 'e' 'i' 'o' 'u']

ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [4]:
#Write your answer here

import numpy as np

# Arrays from the previous question
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# 1. Find dimensions, shape, size, data type, and item size
arrays = [zeros, vowels, ones, myarray1, myarray2]
for array in arrays:
    print(f"Array:\n{array}")
    print(f"Dimensions (ndim): {array.ndim}")
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Data type (dtype): {array.dtype}")
    print(f"Item size: {array.itemsize} bytes\n")

# 2. Reshape the array 'ones' to have all 10 elements in a single row
ones_reshaped = ones.reshape(1, 10)
print("Reshaped array 'ones':\n", ones_reshaped)

# 3. Display the 2nd and 3rd element of the array 'vowels'
print("\n2nd and 3rd elements of 'vowels':", vowels[1:3])

# 4. Display all elements in the 2nd and 3rd row of the array 'myarray1'
print("\nElements in the 2nd and 3rd row of 'myarray1':\n", myarray1[1:3, :])

# 5. Display the elements in the 1st and 2nd column of the array 'myarray1'
print("\nElements in the 1st and 2nd column of 'myarray1':\n", myarray1[:, 0:2])

# 6. Display the elements in the 1st column of the 2nd and 3rd row of 'myarray1'
print("\n1st column of 2nd and 3rd row of 'myarray1':\n", myarray1[1:3, 0])

# 7. Reverse the array 'vowels'
vowels_reversed = vowels[::-1]
print("\nReversed 'vowels':", vowels_reversed)


Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensions (ndim): 1
Shape: (10,)
Size: 10
Data type (dtype): float64
Item size: 8 bytes

Array:
['a' 'e' 'i' 'o' 'u']
Dimensions (ndim): 1
Shape: (5,)
Size: 5
Data type (dtype): <U1
Item size: 4 bytes

Array:
[[1 1 1 1 1]
 [1 1 1 1 1]]
Dimensions (ndim): 2
Shape: (2, 5)
Size: 10
Data type (dtype): int64
Item size: 8 bytes

Array:
[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Dimensions (ndim): 2
Shape: (3, 3)
Size: 9
Data type (dtype): float64
Item size: 8 bytes

Array:
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]
Dimensions (ndim): 2
Shape: (3, 5)
Size: 15
Data type (dtype): float64
Item size: 8 bytes

Reshaped array 'ones':
 [[1 1 1 1 1 1 1 1 1 1]]

2nd and 3rd elements of 'vowels': ['e' 'i']

Elements in the 2nd and 3rd row of 'myarray1':
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

Elements in the 1st and 2nd column of 'myarray1':
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]

1st column of 2nd and 

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [12]:
import numpy as np

# Trim myarray2 to match the shape of myarray1 (trim columns)
myarray2_trimmed = myarray2[:, :3]

# 1. Add the arrays
added_arrays = myarray1 + myarray2_trimmed
print("\nSum of 'myarray1' and trimmed 'myarray2':\n", added_arrays)

# 2. Subtract myarray1 from myarray2_trimmed
subtracted_arrays = myarray2_trimmed - myarray1
print("\nDifference between trimmed 'myarray2' and 'myarray1':\n", subtracted_arrays)

# 3. Multiply myarray1 and myarray2_trimmed elementwise
elementwise_multiplication = myarray1 * myarray2_trimmed
print("\nElementwise multiplication of 'myarray1' and trimmed 'myarray2':\n", elementwise_multiplication)

# 4. Matrix multiplication of myarray1 and myarray2_trimmed
try:
    myarray3 = np.dot(myarray1, myarray2_trimmed.T)
    print("\nMatrix multiplication of 'myarray1' and 'trimmed myarray2' (myarray3):\n", myarray3)
except ValueError:
    print("\nMatrix multiplication is not possible due to shape mismatch.")

# 5. Divide myarray1 by myarray2_trimmed
division_result = np.divide(myarray1, myarray2_trimmed)
print("\nDivision of 'myarray1' by 'myarray2_trimmed':\n", division_result)

# 6. Cube of all elements of myarray1 and divide by 2
cubed_array = (myarray1 ** 3) / 2
print("\nCube of 'myarray1' divided by 2:\n", cubed_array)

# 7. Square root of all elements of myarray2_trimmed, divide by 2, and round to 2 decimal places
sqrt_array = np.sqrt(myarray2_trimmed) / 2
sqrt_array_rounded = np.round(sqrt_array, 2)
print("\nSquare root of 'myarray2_trimmed' divided by 2 (rounded to 2 decimals):\n", sqrt_array_rounded)



Sum of 'myarray1' and trimmed 'myarray2':
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]

Difference between trimmed 'myarray2' and 'myarray1':
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]

Elementwise multiplication of 'myarray1' and trimmed 'myarray2':
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]

Matrix multiplication of 'myarray1' and 'trimmed myarray2' (myarray3):
 [[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]

Division of 'myarray1' by 'myarray2_trimmed':
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]

Cube of 'myarray1' divided by 2:
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]

Square root of 'myarray2_trimmed' divided by 2 (rounded to 2 decimals):
 [[1.   1.41 1.73]
 [2.45 2.65 

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [14]:
# Write your answer here
import numpy as np

# 1. Find the transpose of 'ones' and 'myarray2'
ones_transposed = ones.T
myarray2_transposed = myarray2.T

print("Transpose of 'ones':\n", ones_transposed)
print("\nTranspose of 'myarray2':\n", myarray2_transposed)

# 2. Sort the array 'vowels' in reverse order
vowels_sorted_reverse = np.sort(vowels)[::-1]
print("\n'vowels' sorted in reverse order:\n", vowels_sorted_reverse)

# 3. Sort 'myarray1' so that the lowest value of the column is in the first row, and so on
myarray1_sorted = np.sort(myarray1, axis=0)
print("\n'myarray1' sorted by columns (lowest value in first row):\n", myarray1_sorted)




Transpose of 'ones':
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

Transpose of 'myarray2':
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]

'vowels' sorted in reverse order:
 ['u' 'o' 'i' 'e' 'a']

'myarray1' sorted by columns (lowest value in first row):
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [16]:
# Write your answer here

import numpy as np

# Create a 2-D array myarray4 with 14 rows and 3 columns using arange
start_value = -1
step_size = 0.25
total_elements = 14 * 3  # 14 rows * 3 columns = 42 elements

# Creating the array
myarray4 = np.arange(start_value, start_value + step_size * total_elements, step_size).reshape(14, 3)

print("Original myarray4:\n", myarray4)

# Split the array row-wise into 3 equal parts
split_arrays = np.array_split(myarray4, 3)

# Print the result of the split
print("\nSplitted arrays:")
for idx, arr in enumerate(split_arrays):
    print(f"\nPart {idx + 1}:\n", arr)



Original myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]

Splitted arrays:

Part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

Part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

Part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [18]:
# Write your ansewr here

import numpy as np

# Calculating required statistics
total_sum = np.sum(myarray4)
row_wise_sum = np.sum(myarray4, axis=1)
column_wise_sum = np.sum(myarray4, axis=0)
max_value = np.max(myarray4)
row_wise_min = np.min(myarray4, axis=1)
row_wise_mean = np.mean(myarray4, axis=1)
column_wise_std = np.std(myarray4, axis=0)

# Printing results
print("Total sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_wise_sum)
print("Sum of all elements column-wise:", column_wise_sum)
print("Max of all elements:", max_value)
print("Min of all elements in each row:", row_wise_min)
print("Mean of all elements in each row:", row_wise_mean)
print("Standard deviation column-wise:", column_wise_std)



Total sum of all elements: 173.25
Sum of all elements row-wise: [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
Sum of all elements column-wise: [54.25 57.75 61.25]
Max of all elements: 9.25
Min of all elements in each row: [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
Mean of all elements in each row: [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
Standard deviation column-wise: [3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [41]:
import pandas as pd
import numpy as np

# Step 1: Read the CSV file
file_path = 'country-capital-lat-long-population.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)

# Step 2: Check the column names and the first few rows
print("Columns in the DataFrame:", data.columns.tolist())
print(data.head())

# Step 3: Convert Latitude and Longitude to numeric, forcing errors to NaN
data['Latitude'] = pd.to_numeric(data['Latitude'], errors='coerce')
data['Longitude'] = pd.to_numeric(data['Longitude'], errors='coerce')

# Step 4: Extract coordinates of Riyadh
riyadh_row = data[data['Country'] == 'Saudi Arabia']  # Use the correct column name
riyadh_coords = riyadh_row[['Latitude', 'Longitude']].to_numpy().flatten()  # Get Riyadh's coordinates

# Check for NaN values in Riyadh's coordinates
print(f"Riyadh Coordinates: {riyadh_coords}")
if np.any(np.isnan(riyadh_coords)):
    print("Riyadh coordinates contain NaN values. Check the data.")
else:
    # Step 5: Extract coordinates of all capital cities
    capitals_coords = data[['Capital City', 'Latitude', 'Longitude']].to_numpy()
    print(f"Capitals Coordinates:\n{capitals_coords}")

    # Ensure all coordinates are valid and numeric
    print("Data Types:", capitals_coords.dtype)
    print("Riyadh Latitude:", type(riyadh_coords[0]), "Longitude:", type(riyadh_coords[1]))

    # Step 6: Calculate Euclidean distances
    distances = np.sqrt((capitals_coords[:, 1] - riyadh_coords[0]) ** 2 + 
                        (capitals_coords[:, 2] - riyadh_coords[1]) ** 2)
    print("Distances:", distances)

    # Step 7: Find the index of the closest capital city
    closest_index = np.argmin(distances)

    # Step 8: Print the name and coordinates of the closest capital city
    closest_capital = capitals_coords[closest_index]
    print(f"Closest capital city to Riyadh:")
    print(f"Name: {closest_capital[0]}")
    print(f"Coordinates: Latitude = {closest_capital[1]}, Longitude = {closest_capital[2]}")



Columns in the DataFrame: ['Country', 'Capital City', 'Latitude', 'Longitude', 'Population', 'Capital Type']
          Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital  
Riyadh Coordinates: [24.6905 46.7096]
Capitals Coordinates:
[['Kabul' 34.5289 69.1725]
 ['Tiranë (Tirana)' 41.3275 19.8189]
 ['El Djazaïr  (Algiers)' 36.7525 3.042]
 ['Pago Pago' -14.2781 -170.7025]
 ['Andorra la Vella' 42.5078 1.5211]
 ['Luanda' -8.8368 13.2343]
 ['The Valley' 18.217 -63.0578]
 ["St. John's" 17.1172 -61.845

TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method

#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [45]:
import pandas as pd
import numpy as np

# Read the CSV file
data = pd.read_csv('/Users/reema/Downloads/country-capital-lat-long-population (1).csv')

# Convert Latitude and Longitude to numeric and drop rows with NaN values
data['Latitude'] = pd.to_numeric(data['Latitude'], errors='coerce')
data['Longitude'] = pd.to_numeric(data['Longitude'], errors='coerce')
data.dropna(subset=['Latitude', 'Longitude'], inplace=True)  # Remove rows with NaN coordinates

# Get Washington D.C.'s coordinates
dc_coords = data.loc[data['Capital City'] == 'Washington, D.C.', ['Latitude', 'Longitude']].values.flatten()

# Ensure we have valid coordinates for Washington, D.C.
if dc_coords.size == 0:
    raise ValueError("Washington, D.C. not found in the dataset.")

# Get coordinates of all capital cities
capitals_coords = data[['Country', 'Capital City', 'Latitude', 'Longitude']].values

# Calculate Euclidean distances to Washington D.C.
distances = np.sqrt((capitals_coords[:, 2] - dc_coords[0]) ** 2 + (capitals_coords[:, 3] - dc_coords[1]) ** 2)

# Get indices of the top 10 closest capital cities
closest_indices = np.argsort(distances)[:10]

# Print the names of the countries and their coordinates
print("Top 10 closest capital cities to Washington D.C.:")
for index in closest_indices:
    country = capitals_coords[index, 0]
    capital = capitals_coords[index, 1]
    coords = capitals_coords[index, 2:4]  # Get latitude and longitude
    print(f"{country} - {capital}: (Latitude: {coords[0]}, Longitude: {coords[1]})")

# Create and print a NumPy array containing the coordinates of the top 10 cities
top_10_coords = capitals_coords[closest_indices, 2:4]  # Extract only Latitude and Longitude
print("\nCoordinates of the top 10 closest capital cities:")
print(top_10_coords)



TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method